start_yr: 1982
timeframes:
  train_12:
    last_train_year: 1993
    end_yr: 2013
    timeframe: "past"
  train_22:
    last_train_year: 2003
    end_yr: 2013
    timeframe: "past"
  train_32:
    last_train_year: 2013
    end_yr: 2050
    timeframe: "future"
min_year_percentage: 70
vars: 
  - bio2 #Mean Diurnal Range (Mean of monthly (max temp - min temp))
  - bio3 #Isothermality (BIO2/BIO7) (* 100)
  - bio5 #Max Temperature of Warmest Month
  - bio8 #Mean Temperature of Wettest Quarter
  - bio9 #Mean Temperature of Driest Quarter
  - bio15 #Precipitation Seasonality (Coefficient of Variation)
  - bio16 #Precipitation of Wettest Quarter
  - bio18 #Precipitation of Warmest Quarter
  - ndvi_sum 
  - ndvi_win
  - elevs

#These variables are used in bio3 and bio7
#BIO5 = Max Temperature of Warmest Month
#BIO6 = Min Temperature of Coldest Month
#BIO7 = Temperature Annual Range (BIO5-BIO6)
